import hashlib
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools"))
import web_asset_guard as guard  # noqa: E402


def fake_rom(title=b"TESTTITLE", code=b"ZZZE", size=0x200):
    # Synthetic header: no Nintendo logo bytes, only the fields the guard checks.
    data = bytearray(size)
    data[0:4] = bytes([0x2E, 0x00, 0x00, 0xEA])
    data[0xA0:0xA0 + len(title)] = title
    data[0xAC:0xB0] = code
    data[0xB2] = 0x96
    data[0xBD] = guard.gba_header_complement(data)
    return bytes(data)


FAKE_BIOS = bytes(range(256)) * 64  # 16384 bytes, not Nintendo's
FAKE_BIOS_SHA1 = hashlib.sha1(FAKE_BIOS).hexdigest()


class GuardTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)

    def tearDown(self):
        self.tmp.cleanup()

    def write(self, rel, data):
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return path

    def kinds(self):
        return sorted(f.kind for f in guard.scan_tree(self.root, FAKE_BIOS_SHA1))

    def test_rom_detected_by_content_under_any_name(self):
        self.write("assets/data.bin", fake_rom())
        self.assertEqual(self.kinds(), ["rom"])

    def test_broken_header_is_not_a_rom(self):
        rom = bytearray(fake_rom())
        rom[0xBD] ^= 1
        self.write("x.dat", bytes(rom))
        self.assertEqual(self.kinds(), [])

    def test_forbidden_names(self):
        self.write("game.gba", b"not a rom")
        self.write("rom_sha1.js", b"x")
        self.write("slot.SAV", b"x")
        self.assertEqual(self.kinds(), ["name", "name", "name"])

    def test_bios_by_hash_only(self):
        self.write("bios.img", FAKE_BIOS)
        self.write("other.bin", bytes(16384))
        self.assertEqual(self.kinds(), ["bios"])

    def test_generated_code(self):
        self.write("gen/recompiled_000.cpp", b"// AUTO-GENERATED by gba_recompile. DO NOT EDIT.\n")
        self.assertEqual(self.kinds(), ["generated"])

    def test_allowlisted_generated_path(self):
        rel = "src/runtime/generated_bios/bios_dispatch_table.cpp"
        path = self.write(rel, b"// AUTO-GENERATED by gba_recompile. DO NOT EDIT.\n")
        self.assertEqual(guard.scan_file(path, rel, FAKE_BIOS_SHA1), [])

    def test_real_bios_hash_is_parsed(self):
        self.assertRegex(guard.parse_bios_sha1(), r"^[0-9a-f]{40}$")

    def test_cli_exit_codes(self):
        script = str(REPO / "tools" / "web_asset_guard.py")
        cmd = [sys.executable, script, "--bios-sha1", FAKE_BIOS_SHA1, str(self.root)]
        self.write("index.html", b"<title>ok</title>")
        self.assertEqual(subprocess.run(cmd, capture_output=True).returncode, 0)
        self.write("game.wasm.bak", fake_rom())
        result = subprocess.run(cmd, capture_output=True, text=True)
        self.assertEqual(result.returncode, 1)
        self.assertIn("rom:", result.stdout)
        self.assertEqual(subprocess.run([sys.executable, script], capture_output=True).returncode, 2)


if __name__ == "__main__":
    unittest.main()
