#!/bin/bash
# Build a browser bundle for an exported game project (tools/cli.py build ...).
#
#   packaging/web/build_web.sh [--rom-sha1 HEX] <project dir> <generated BIOS dir>
#
# Produces <project dir>/web/{index.html,game.js,game.wasm,manifest.json,...}.
# Serve it with packaging/web/serve.py (COOP/COEP are required for pthreads).
# The ROM and BIOS are never copied into the bundle (LEGAL.md): the visitor
# loads their own dumps in the page, checked against manifest.json "assets".
#
# Isolated build/output directories: GBARECOMP_WEB_BUILD_DIR (runtime),
# GBARECOMP_WEB_GAME_BUILD_DIR (game library), GBARECOMP_WEB_OUT_DIR (bundle).
# The runtime is configured with -DGBARECOMP_WEB_HOST=ON: no SDL, no
# OffscreenCanvas; host_web.js, bootstrap.js and the AudioWorklet DSP bundle
# are always copied so JS-only changes reach the output without a ROM rebuild.
#
# Threading model: -sPROXY_TO_PTHREAD. main() and the whole guest run on a Web
# Worker, where the blocking run loop and present-in-place are legal; the
# page owns WebGL; the worker only publishes shared RGB/PCM. Generated
# code needs guaranteed tail calls, so everything is built with -mtail-call
# (runtime_arm.h refuses to compile otherwise).
#
# Saves: /saves is an IDBFS mount (never -sWASMFS, which cannot link it)
# synced explicitly by save_store.js. Product link flags are generated by the
# runtime CMake configure into gbarecomp_web_host_link_options.rsp.
#
# The recompiler itself never runs here: generate the project and the BIOS with
# a native build first. There is no self-heal compiler in a browser, so a web
# build is only honest for a game whose coverage is FULLY STATIC.
set -euo pipefail

ROM_SHA1_ARGS=()
if [ "${1:-}" = "--rom-sha1" ]; then
  [ $# -ge 2 ] || { echo "error: --rom-sha1 needs a value" >&2; exit 2; }
  ROM_SHA1_ARGS=(--rom-sha1 "$2")
  shift 2
fi
if [ $# -gt 2 ]; then
  echo "error: ROM and BIOS are never copied into a browser bundle (LEGAL.md)." >&2
  echo "       Load them in the page; for local tests use packaging/web/serve.py <bundle> --dev-assets <dir>." >&2
  exit 2
fi
if [ $# -lt 2 ]; then
  sed -n '2,8p' "$0"
  exit 2
fi

R=$(cd "$(dirname "$0")/../.." && pwd)
PROJECT=$(cd "$1" && pwd)
BIOS_GEN=$(cd "$2" && pwd)
JOBS=${JOBS:-$(sysctl -n hw.ncpu 2>/dev/null || nproc)}
absolute_dir() { mkdir -p "$1"; (cd "$1" && pwd); }
B=$(absolute_dir "${GBARECOMP_WEB_BUILD_DIR:-$R/build-web-host}")
GAME_BUILD=$(absolute_dir "${GBARECOMP_WEB_GAME_BUILD_DIR:-$PROJECT/build-web-host}")
OUT=$(absolute_dir "${GBARECOMP_WEB_OUT_DIR:-$PROJECT/web}")
check_cache() {
  if [ -f "$1/CMakeCache.txt" ] && ! grep -Fxq "CMAKE_HOME_DIRECTORY:INTERNAL=$2" "$1/CMakeCache.txt"; then
    echo "error: CMake cache in $1 belongs to another source tree" >&2; exit 1
  fi
}
check_cache "$B" "$R"
check_cache "$GAME_BUILD" "$PROJECT"
if ! STALE=$(python3 "$R/packaging/web/bundle_policy.py" stale "$OUT"); then
  echo "error: $OUT still holds ROM/BIOS copies from an older build_web.sh:" >&2
  echo "$STALE" >&2
  echo "       move them out of the bundle (e.g. to a --dev-assets dir, see docs/WEB_PRIVATE_TEST_HOSTING.md) and rerun" >&2
  exit 1
fi
python3 "$R/packaging/web/bundle_policy.py" expected "$PROJECT" ${ROM_SHA1_ARGS[@]+"${ROM_SHA1_ARGS[@]}"}
for source in bios_recompiled.cpp bios_dispatch_table.cpp; do
  test -s "$BIOS_GEN/$source" || { echo "error: missing generated BIOS $source" >&2; exit 1; }
done

if ! command -v emcc > /dev/null; then
  # shellcheck disable=SC1091
  source "${EMSDK:-$HOME/emsdk}/emsdk_env.sh" > /dev/null
fi
echo "== runtime (wasm, pthreads) -> $B"
emcmake cmake -S "$R" -B "$B" -DCMAKE_BUILD_TYPE=Release \
  -DGBARECOMP_COMPILER_CACHE=OFF \
  -DCMAKE_C_FLAGS=-pthread -DCMAKE_CXX_FLAGS=-pthread \
  -DGBARECOMP_WEB_HOST=ON \
  -DGBARECOMP_GENERATED_BIOS_DIR="$BIOS_GEN" > "$B.configure.log"
grep -q "BIOS recompiled output present" "$B.configure.log" || {
  echo "error: runtime configure did not pick up the recompiled BIOS" >&2; exit 1; }
grep -q "host_backend=web" "$B.configure.log" || {
  echo "error: browser backend was not selected" >&2; exit 1; }
WEB_LINK_OPTIONS="$B/gbarecomp_web_host_link_options.rsp"
test -s "$WEB_LINK_OPTIONS" || {
  echo "error: runtime configure did not generate browser link options" >&2; exit 1; }
WEB_LINK_ARGS=()
while IFS= read -r option; do
  test -n "$option" && WEB_LINK_ARGS+=("$option")
done < "$WEB_LINK_OPTIONS"
cmake --build "$B" --target gbarecomp_runtime gbarecomp_debug gbarecomp_gba \
  gbarecomp_armv4t gbarecomp_recompile_core gbarecomp_heal_gate -- -j"$JOBS"

echo "== game library (wasm, pthreads) -> $GAME_BUILD"
grep -q -- "-mtail-call" "$PROJECT/CMakeLists.txt" || {
  echo "error: $PROJECT/CMakeLists.txt predates guaranteed tail calls; regenerate it with tools/cli.py" >&2
  exit 1; }
emcmake cmake -S "$PROJECT" -B "$GAME_BUILD" -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_FLAGS=-pthread > /dev/null
cmake --build "$GAME_BUILD" -- -j"$JOBS"

echo "== link -> $OUT"
mkdir -p "$OUT"
em++ -O2 -std=c++20 \
  -I"$R/src/runtime" -I"$R/src/armv4t" -I"$R/src/gba" -I"$R/src/debug" \
  -I"$R/external/arm-recomp-core/profiles/armv4t_gba" \
  "$R/packaging/web/main.cpp" \
  -Wl,--start-group \
    "$B/libgbarecomp_runtime.a" "$B/libgbarecomp_debug.a" "$B/libgbarecomp_gba.a" \
    "$B/libgbarecomp_armv4t.a" "$B/libgbarecomp_recompile_core.a" \
    "$B/libgbarecomp_heal_gate.a" "$GAME_BUILD/libgbarecomp_game.a" \
  -Wl,--end-group \
  "${WEB_LINK_ARGS[@]}" \
  -o "$OUT/game.js"

echo "== independent AudioWorklet DSP"
em++ -O2 -std=c++20 -I"$R/src/runtime" "$R/src/runtime/host_web_audio_dsp.cpp" --no-entry \
  -sENVIRONMENT=worklet -sMODULARIZE=1 -sEXPORT_NAME=createGbrAudioDSP \
  -sSINGLE_FILE -sWASM_ASYNC_COMPILATION=0 -sFILESYSTEM=0 \
  -sEXPORTED_RUNTIME_METHODS=HEAP16 -sINITIAL_MEMORY=16777216 \
  -o "$OUT/audio_dsp.js"
cat "$OUT/audio_dsp.js" "$R/packaging/web/audio_worklet.js" > "$OUT/audio_worklet_bundle.js"
cp "$R/packaging/web/index.html" "$R/packaging/web/host_web.js" "$R/packaging/web/save_store.js" "$R/packaging/web/asset_store.js" "$R/packaging/web/bootstrap.js" "$R/packaging/web/audio_worklet.js" "$OUT/"
printf 'User-agent: *\nDisallow: /\n' > "$OUT/robots.txt"
python3 "$R/packaging/web/bundle_policy.py" manifest "$R" "$OUT" "$BIOS_GEN" "$PROJECT" \
  ${ROM_SHA1_ARGS[@]+"${ROM_SHA1_ARGS[@]}"}
python3 "$R/tools/web_asset_guard.py" "$OUT"
ls -la "$OUT" | grep -v ' \._'
echo "== done. serve with: python3 $R/packaging/web/serve.py $OUT  (load your own ROM + BIOS in the page)"
