#!/usr/bin/env python3
"""Refuse GBA ROMs, BIOS images and gba_recompile output where they must never be.

A GBA ROM or BIOS, or C++ emitted by gba_recompile from one, is the rights
holder's work or an adaptation of it (see LEGAL.md). Scans:
  --git        files tracked or staged in the current repository (pre-commit, ctest)
  <dir> ...    directory trees, e.g. a browser bundle before it is served or uploaded

Detection is by content, never by trusting a file name:
  rom        valid GBA cartridge header (0x96 at 0xB2 and header complement at 0xBD)
  bios       exactly 16384 bytes whose SHA-1 is the retail BIOS (src/gba/gba_bios.h)
  generated  the gba_recompile banner in the first bytes, outside ALLOWED_GENERATED
  name       .gba/.agb/.sav files and rom_sha1.js, whatever their content
Exit 0 = clean, 1 = findings (one per line), 2 = usage error.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BIOS_HEADER = REPO / "src" / "gba" / "gba_bios.h"
BIOS_SIZE = 16 * 1024
GENERATED_MARKER = b"AUTO-GENERATED by gba_recompile"
FORBIDDEN_SUFFIXES = {".gba", ".agb", ".sav"}
FORBIDDEN_NAMES = {"rom_sha1.js"}
# Tracked files that carry the banner but no guest instructions.
ALLOWED_GENERATED = {
    # BIOS address -> function-name table (see src/runtime/generated_bios/.gitignore).
    "src/runtime/generated_bios/bios_dispatch_table.cpp",
    # The emitter: the banner is a string literal it writes.
    "tools/gba_recompile/main.cpp",
}
HEAD_BYTES = 4096


@dataclass(frozen=True)
class Finding:
    path: str
    kind: str
    detail: str

    def __str__(self) -> str:
        return f"{self.kind}: {self.path}: {self.detail}"


def parse_bios_sha1(header: Path = BIOS_HEADER) -> str:
    match = re.search(r'kExpectedSha1\s*=\s*"([0-9a-f]{40})"', header.read_text())
    if not match:
        raise ValueError(f"kExpectedSha1 not found in {header}")
    return match.group(1)


def gba_header_complement(data: bytes) -> int:
    return (-(sum(data[0xA0:0xBD]) + 0x19)) & 0xFF


def looks_like_gba_rom(data: bytes) -> bool:
    return (len(data) >= 0xC0 and data[0xB2] == 0x96
            and data[0xBD] == gba_header_complement(data))


def scan_file(path: Path, rel: str, bios_sha1: str) -> list[Finding]:
    findings: list[Finding] = []
    if path.name in FORBIDDEN_NAMES or path.suffix.lower() in FORBIDDEN_SUFFIXES:
        findings.append(Finding(rel, "name", f"{path.name} must never be tracked or bundled"))
    try:
        size = path.stat().st_size
        with path.open("rb") as f:
            head = f.read(HEAD_BYTES)
    except OSError as e:
        return findings + [Finding(rel, "unreadable", str(e))]
    if looks_like_gba_rom(head):
        title = head[0xA0:0xAC].decode("latin-1").strip("\0 ")
        code = head[0xAC:0xB0].decode("latin-1")
        findings.append(Finding(rel, "rom", f'GBA cartridge header "{title}" ({code})'))
    if size == BIOS_SIZE and hashlib.sha1(path.read_bytes()).hexdigest() == bios_sha1:
        findings.append(Finding(rel, "bios", "retail GBA BIOS image"))
    if GENERATED_MARKER in head and rel not in ALLOWED_GENERATED:
        findings.append(Finding(rel, "generated", "gba_recompile output is an adaptation of a ROM/BIOS"))
    return findings


def scan_tree(root: Path, bios_sha1: str) -> list[Finding]:
    findings: list[Finding] = []
    for path in sorted(p for p in root.rglob("*") if p.is_file()):
        findings += scan_file(path, path.relative_to(root).as_posix(), bios_sha1)
    return findings


def scan_git(top: Path, bios_sha1: str) -> list[Finding]:
    listed = subprocess.run(["git", "-C", str(top), "ls-files", "-z", "--cached"],
                            check=True, capture_output=True).stdout
    findings: list[Finding] = []
    for rel in filter(None, listed.decode("utf-8", "surrogateescape").split("\0")):
        path = top / rel
        if path.is_file():  # skips submodule gitlinks and files deleted in the worktree
            findings += scan_file(path, rel, bios_sha1)
    return findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--git", action="store_true", help="scan files tracked or staged here")
    parser.add_argument("dirs", nargs="*", type=Path, help="directory trees to scan")
    parser.add_argument("--bios-sha1", help=argparse.SUPPRESS)  # tests only
    args = parser.parse_args(argv)
    if not args.git and not args.dirs:
        parser.print_usage(sys.stderr)
        return 2
    bios_sha1 = args.bios_sha1 or parse_bios_sha1()
    findings: list[Finding] = []
    if args.git:
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                             check=True, capture_output=True, text=True).stdout.strip()
        findings += scan_git(Path(top), bios_sha1)
    for directory in args.dirs:
        if not directory.is_dir():
            print(f"error: not a directory: {directory}", file=sys.stderr)
            return 2
        findings += [Finding(f"{directory}/{f.path}", f.kind, f.detail)
                     for f in scan_tree(directory, bios_sha1)]
    for finding in findings:
        print(finding)
    if findings:
        print(f"web_asset_guard: {len(findings)} finding(s); see LEGAL.md", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
